language: csharp
dist: bionic
mono: latest
dotnet: 2.2
solution: ObjectOrientedDB.sln

git:
  depth: false

script:
- dotnet build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: ObjectOrientedDB/_site
  keep_history: true
  on:
    branch: master
