language: csharp
dist: bionic
mono: latest
solution: ObjectOrientedDB.sln

git:
  depth: false

install:
- msbuild -r

before_script:
- nuget install docfx.console -ExcludeVersion
- export DOCFX='mono docfx.console/tools/docfx.exe'

script:
- msbuild /p:Configuration=Release ObjectOrientedDB.sln

# Doc
- $DOCFX metadata ObjectOrientedDB/docfx.json
- $DOCFX build ObjectOrientedDB/docfx.json

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: ObjectOrientedDB/_site
  keep_history: true
  on:
    branch: master
