language: csharp
dist: bionic
mono: latest
dotnet: 2.2
solution: ObjectOrientedDB.sln

git:
  depth: false

script:
- dotnet build

deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: ObjectOrientedDB/_site
  keep_history: true
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script:
    - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - export NUGET='mono nuget.exe'
    - $NUGET pack ./ObjectOrientedDB.nuspec
    - $NUGET setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
    - $NUGET push ObjectOrientedDB.*.nupkg -Source $NUGET_SOURCE
    - /bin/sh ./deploy.sh
  on:
    tags: true
