language: csharp
dist: trusty
mono: none
dotnet: 2.2
solution: ObjectOrientedDB.sln

git:
  depth: false

before_script:
- nuget install docfx.console -ExcludeVersion
- export DOCFX='mono docfx.console/tools/docfx.exe'

script:
# Build
- dotnet build

# Test
- dotnet test

# Doc
- $DOCFX metadata ObjectOrientedDB/docfx.json
- $DOCFX build ObjectOrientedDB/docfx.json

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: ObjectOrientedDB/_site
  keep_history: true
  on:
    branch: master
