@startuml
participant Consumer
participant ObjectDB
participant Index
participant Datastore

Consumer -> ObjectDB ++: Delete(GUID)

ObjectDB -> Index ++: Delete(GUID)
Index -> ObjectDB --: oldDataPosition

ObjectDB -> Datastore ++: Delete(oldDataPosition)
Datastore -> ObjectDB --

ObjectDB -> Consumer --

@enduml
