@startuml
participant Consumer
participant ObjectDB
participant Index
participant Datastore
participant Serializer

Consumer -> ObjectDB ++: Find(GUID)

ObjectDB -> Index ++: Find(GUID)
Index -> ObjectDB --: dataPosition

ObjectDB -> Datastore ++: Read(dataPosition)
Datastore -> ObjectDB --: byte[]

ObjectDB  -> Serializer ++: Deserialize(byte[])
Serializer -> ObjectDB --: Object

ObjectDB -> Consumer --: Object

@enduml
