@startuml
participant Consumer
participant ObjectDB
participant Serializer
participant StorageEngine
participant GuidGenerator
participant BinarySearchTree

Consumer -> ObjectDB ++: Save(Serializable)

ObjectDB  -> Serializer ++: Serialize(Serializable)
Serializer -> ObjectDB --: byte[]

ObjectDB -> StorageEngine ++: Insert(byte[])

StorageEngine -> StorageEngine: InsertData(byte[])

StorageEngine -> GuidGenerator ++: NewGuid()
GuidGenerator -> StorageEngine --: GUID

StorageEngine -> BinarySearchTree ++: AddEntry(GUID, dataPosition)
BinarySearchTree -> StorageEngine --

StorageEngine -> ObjectDB --: GUID

ObjectDB -> Consumer --: GUID

@enduml
