@startuml
participant Consumer
participant ObjectDB
participant Serializer
participant Datastore
participant Index

Consumer -> ObjectDB ++: Update(GUID, Serializable)

ObjectDB  -> Serializer ++: Serialize(Serializable)
Serializer -> ObjectDB --: byte[]

ObjectDB -> Index ++: Find(GUID)
Index -> ObjectDB --: oldDataPosition

ObjectDB -> Datastore ++: Insert(byte[])
Datastore -> ObjectDB --: newDataPosition

ObjectDB -> Index ++: Update(GUID, newDataPosition)
Index -> ObjectDB --

ObjectDB -> Datastore ++: Delete(oldDataPosition)
Datastore -> ObjectDB --

ObjectDB -> Consumer --

@enduml
